language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "moseskim-github"
    token:
      secure: "1ee9fa447db327642f32bf071f3dcf8bdc729d62"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
